spring.application.name=event-booking-platform

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/event_booking_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Event2026}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE
logging.level.com.eventbooking.event_booking_platform=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE